version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        WP_API_BASE: ${WP_API_BASE:?set WP_API_BASE}
        WP_ADMIN_USER: ${WP_ADMIN_USER:-}
        WP_APP_PASSWORD: ${WP_APP_PASSWORD:-}
        WEBHOOK_SECRET: ${WEBHOOK_SECRET:-}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL:?set DATABASE_URL}
      NEXT_PUBLIC_SITE_URL: ${SITE_URL:?set SITE_URL}
      NEXT_PUBLIC_GA_MEASUREMENT_ID: ${NEXT_PUBLIC_GA_MEASUREMENT_ID:-}
      NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION: ${NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION:-}
      S3_BUCKET: ${S3_BUCKET:-}
      S3_ENDPOINT: ${S3_ENDPOINT:-}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-}
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/production.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/acme:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
      - ./dhparam:/etc/ssl/dhparam
    environment:
      SITE_HOSTNAME: ${SITE_HOSTNAME:?set SITE_HOSTNAME}
      APP_UPSTREAM: ${APP_UPSTREAM:-app:3000}
    command: >-
      /bin/sh -c "envsubst '$$SITE_HOSTNAME $$APP_UPSTREAM' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    entrypoint: 
      - /bin/sh
      - -c
      - |
        trap "exit 0" TERM INT
        while true; do
          certbot renew --webroot -w /var/www/certbot && nginx -s reload || true
          sleep 12h
        done
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./nginx/acme:/var/www/certbot
    depends_on:
      - nginx
    restart: unless-stopped

#  backups:
#    build:
#      context: ./backups
#      dockerfile: Dockerfile
#    entrypoint: ["/bin/bash", "/scripts/pg_backup.sh"]
#    environment:
#      DATABASE_URL: ${DATABASE_URL:?set DATABASE_URL}
#      BACKUP_S3_BUCKET: ${BACKUP_S3_BUCKET:-}
#      BACKUP_S3_ENDPOINT: ${BACKUP_S3_ENDPOINT:-}
#      BACKUP_S3_ACCESS_KEY: ${BACKUP_S3_ACCESS_KEY:-}
#      BACKUP_S3_SECRET_KEY: ${BACKUP_S3_SECRET_KEY:-}
#      BACKUP_RETENTION_DAYS: ${BACKUP_RETENTION_DAYS:-7}
#    volumes:
#      - ./backups:/scripts:ro
#      - backups:/backups
#    restart: "no"

volumes:
  letsencrypt:
  backups:
