version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: indiainflation
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --address :9000 --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    command: npm run dev
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:password@postgres:5432/indiainflation
      NEXT_PUBLIC_API_BASE: http://localhost:3000/api
    ports:
      - "3000:3000"
    volumes:
      - ../web:/app
    depends_on:
      - postgres

  etl:
    build:
      context: ../etl
      dockerfile: Dockerfile
    command: python -m etl.fetch_mospi file:///app/tests/fixtures/sample_annex.xlsx --dry-run
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:password@postgres:5432/indiainflation
    volumes:
      - ../etl:/app
    depends_on:
      - postgres

volumes:
  pgdata:
  miniodata:
