name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json
      - run: npm install --force
        working-directory: web
      - run: npm run lint
        working-directory: web
      - run: npm test
        working-directory: web

  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r etl/requirements.txt
      - run: pytest
        working-directory: etl
